### ISSUE TITLE
Add the read me file

### ISSUE THREAD

**Issue by Praveen-Oruganti** [Praveen-Oruganti/demo#2]
Hi Tharun Babu,

Can you helpme in adding the content into the Readme.md file of our repo.

Thank You
Praveen-Oruganti

**Comment by tharunbabu6675** [comment]
ok i will do
[Uploading WCC Mod3@AzDOCUMENTS.in.pdf…]()

**Comment by tharunbabu6675** [comment]
i will do
[Uploading WCC Mod3@AzDOCUMENTS.in.pdf…]()

**Comment by Praveen-Oruganti** [comment]
hhelo
